language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_script:
  - composer install

notifications:
  email:
    - michal@michaldudek.pl

matrix:
  exclude:
  allow_failures:
    - php: hhvm
